name: Тести

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout коду
      uses: actions/checkout@v2

    - name: Настановлення Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Встановлення залежностей
      run: pip install -r requirements.txt
    
    - name: Запуск тестів
      run: pytest
